### ISSUE TITLE
Errors With Enriched Customer Tagging -  Undefined offset: 1 in Customer.php on Line 122

### ISSUE THREAD

**Issue by mindfriction** [Nosto/nosto-magento#480] opened 2019-01-25 13:28 UTC
Hello,

After updated to the latest version 3.8.2, I get the following errors in Magento:

Notice: Undefined offset: 1  in /html/app/code/community/Nosto/Tagging/Block/Customer.php on line 122

Line 122: $nostoCustomer->setStreet($customerAddress->getStreet()[0].' '.$customerAddress->getStreet()[1]);

**Comment by mridang** [comment] 2019-01-25 13:40
@mindfriction What version of Magento are you running BTW?

**Comment by mindfriction** [comment] 2019-01-25 13:43
Hi @mridang 
I'm running v 1.9.4.0

**Comment by hannunosto** [comment] 2019-01-28 07:55
Thanks for reporting @mindfriction. We will add a nullcheck to this in the next release. It should be released within a few days.

**Closed as completed** 2019-01-28 11:33 UTC
Labels: bug

**Comment by hannunosto** [comment] 2019-01-28 12:23
@mindfriction the fix is out https://github.com/Nosto/nosto-magento/releases/tag/3.8.3. Please comment here if the issue is not solved in 3.8.3
